name: Cleanup acceptance environments

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    container: quay.io/hypernode/deploy:3-php8.1-node18
    steps:
      - uses: actions/checkout@v3
      - name: Cleanup acceptance environments
        run: hypernode-deploy cleanup acceptance -vvv
        env:
          HYPERNODE_API_TOKEN: ${{ secrets.HYPERNODE_API_TOKEN }}
