name: Deploy

on:
  push:

jobs:
    deploy_staging:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/staging'
        container: hipex/deploy:v2.13.0-alpha.1-php8.1-node18
        steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
          with:
              path: /tmp/composer-cache
              key: ${{ runner.os }}-composer
        - uses: webfactory/ssh-agent@v0.5.4
          with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - run: hipex-deploy deploy staging
