name: deploy

on: push

jobs:
  deploy_staging:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/staging'
        container: hipex/deploy:v2.13.0-alpha.1-php8.1-node18
        steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
        - uses: webfactory/ssh-agent@v0.5.4
          with:
              ssh-private-key: ${{ secrets.PRIVATE_KEY }}
        - run: hipex-deploy build
        - run: hipex-deploy deploy staging
