name: deploy

on: push

env:
  COMPOSER_CACHE_DIR: /tmp/composer-cache

defaults:
  run:
    shell: bash

jobs:
  deploy_staging:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/setup-deploy-production1135'
        container: hipex/deploy:v2.13.0-alpha.1-php8.1-node18
        steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
          with:
            path: /tmp/composer-cache
            key: ${{ runner.os }}-composer
        - uses: webfactory/ssh-agent@v0.5.4
          with:
              ssh-private-key: ${{ secrets.PRIVATE_KEY }}
        - run: hipex-deploy build -vvv
        - run: hipex-deploy deploy staging -vvv
